// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automaton.proto

#ifndef PROTOBUF_automaton_2eproto__INCLUDED
#define PROTOBUF_automaton_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_automaton_2eproto();
void protobuf_AssignDesc_automaton_2eproto();
void protobuf_ShutdownFile_automaton_2eproto();

class ProtoNode;
class ProtoNode_Edge;
class ProtoAutomaton;

// ===================================================================

class ProtoNode_Edge : public ::google::protobuf::Message {
 public:
  ProtoNode_Edge();
  virtual ~ProtoNode_Edge();

  ProtoNode_Edge(const ProtoNode_Edge& from);

  inline ProtoNode_Edge& operator=(const ProtoNode_Edge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoNode_Edge& default_instance();

  void Swap(ProtoNode_Edge* other);

  // implements Message ----------------------------------------------

  ProtoNode_Edge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoNode_Edge& from);
  void MergeFrom(const ProtoNode_Edge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 edge_char = 1;
  inline bool has_edge_char() const;
  inline void clear_edge_char();
  static const int kEdgeCharFieldNumber = 1;
  inline ::google::protobuf::int32 edge_char() const;
  inline void set_edge_char(::google::protobuf::int32 value);

  // required int64 to_node_id = 2;
  inline bool has_to_node_id() const;
  inline void clear_to_node_id();
  static const int kToNodeIdFieldNumber = 2;
  inline ::google::protobuf::int64 to_node_id() const;
  inline void set_to_node_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ProtoNode.Edge)
 private:
  inline void set_has_edge_char();
  inline void clear_has_edge_char();
  inline void set_has_to_node_id();
  inline void clear_has_to_node_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 to_node_id_;
  ::google::protobuf::int32 edge_char_;
  friend void  protobuf_AddDesc_automaton_2eproto();
  friend void protobuf_AssignDesc_automaton_2eproto();
  friend void protobuf_ShutdownFile_automaton_2eproto();

  void InitAsDefaultInstance();
  static ProtoNode_Edge* default_instance_;
};
// -------------------------------------------------------------------

class ProtoNode : public ::google::protobuf::Message {
 public:
  ProtoNode();
  virtual ~ProtoNode();

  ProtoNode(const ProtoNode& from);

  inline ProtoNode& operator=(const ProtoNode& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoNode& default_instance();

  void Swap(ProtoNode* other);

  // implements Message ----------------------------------------------

  ProtoNode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoNode& from);
  void MergeFrom(const ProtoNode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ProtoNode_Edge Edge;

  // accessors -------------------------------------------------------

  // repeated .ProtoNode.Edge edges = 1;
  inline int edges_size() const;
  inline void clear_edges();
  static const int kEdgesFieldNumber = 1;
  inline const ::ProtoNode_Edge& edges(int index) const;
  inline ::ProtoNode_Edge* mutable_edges(int index);
  inline ::ProtoNode_Edge* add_edges();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >&
      edges() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >*
      mutable_edges();

  // repeated .ProtoNode.Edge rev_edges = 2;
  inline int rev_edges_size() const;
  inline void clear_rev_edges();
  static const int kRevEdgesFieldNumber = 2;
  inline const ::ProtoNode_Edge& rev_edges(int index) const;
  inline ::ProtoNode_Edge* mutable_rev_edges(int index);
  inline ::ProtoNode_Edge* add_rev_edges();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >&
      rev_edges() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >*
      mutable_rev_edges();

  // repeated int64 rev_links = 8;
  inline int rev_links_size() const;
  inline void clear_rev_links();
  static const int kRevLinksFieldNumber = 8;
  inline ::google::protobuf::int64 rev_links(int index) const;
  inline void set_rev_links(int index, ::google::protobuf::int64 value);
  inline void add_rev_links(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      rev_links() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_rev_links();

  // required int64 link = 3;
  inline bool has_link() const;
  inline void clear_link();
  static const int kLinkFieldNumber = 3;
  inline ::google::protobuf::int64 link() const;
  inline void set_link(::google::protobuf::int64 value);

  // required int64 len_actual = 4;
  inline bool has_len_actual() const;
  inline void clear_len_actual();
  static const int kLenActualFieldNumber = 4;
  inline ::google::protobuf::int64 len_actual() const;
  inline void set_len_actual(::google::protobuf::int64 value);

  // required int64 len_within_document = 5;
  inline bool has_len_within_document() const;
  inline void clear_len_within_document();
  static const int kLenWithinDocumentFieldNumber = 5;
  inline ::google::protobuf::int64 len_within_document() const;
  inline void set_len_within_document(::google::protobuf::int64 value);

  // required int64 docs_occurs_in = 6;
  inline bool has_docs_occurs_in() const;
  inline void clear_docs_occurs_in();
  static const int kDocsOccursInFieldNumber = 6;
  inline ::google::protobuf::int64 docs_occurs_in() const;
  inline void set_docs_occurs_in(::google::protobuf::int64 value);

  // required double score_occurs_only = 7;
  inline bool has_score_occurs_only() const;
  inline void clear_score_occurs_only();
  static const int kScoreOccursOnlyFieldNumber = 7;
  inline double score_occurs_only() const;
  inline void set_score_occurs_only(double value);

  // required int64 last_hash = 9;
  inline bool has_last_hash() const;
  inline void clear_last_hash();
  static const int kLastHashFieldNumber = 9;
  inline ::google::protobuf::int64 last_hash() const;
  inline void set_last_hash(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ProtoNode)
 private:
  inline void set_has_link();
  inline void clear_has_link();
  inline void set_has_len_actual();
  inline void clear_has_len_actual();
  inline void set_has_len_within_document();
  inline void clear_has_len_within_document();
  inline void set_has_docs_occurs_in();
  inline void clear_has_docs_occurs_in();
  inline void set_has_score_occurs_only();
  inline void clear_has_score_occurs_only();
  inline void set_has_last_hash();
  inline void clear_has_last_hash();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge > edges_;
  ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge > rev_edges_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > rev_links_;
  ::google::protobuf::int64 link_;
  ::google::protobuf::int64 len_actual_;
  ::google::protobuf::int64 len_within_document_;
  ::google::protobuf::int64 docs_occurs_in_;
  double score_occurs_only_;
  ::google::protobuf::int64 last_hash_;
  friend void  protobuf_AddDesc_automaton_2eproto();
  friend void protobuf_AssignDesc_automaton_2eproto();
  friend void protobuf_ShutdownFile_automaton_2eproto();

  void InitAsDefaultInstance();
  static ProtoNode* default_instance_;
};
// -------------------------------------------------------------------

class ProtoAutomaton : public ::google::protobuf::Message {
 public:
  ProtoAutomaton();
  virtual ~ProtoAutomaton();

  ProtoAutomaton(const ProtoAutomaton& from);

  inline ProtoAutomaton& operator=(const ProtoAutomaton& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoAutomaton& default_instance();

  void Swap(ProtoAutomaton* other);

  // implements Message ----------------------------------------------

  ProtoAutomaton* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoAutomaton& from);
  void MergeFrom(const ProtoAutomaton& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ProtoNode nodes_pool = 1;
  inline int nodes_pool_size() const;
  inline void clear_nodes_pool();
  static const int kNodesPoolFieldNumber = 1;
  inline const ::ProtoNode& nodes_pool(int index) const;
  inline ::ProtoNode* mutable_nodes_pool(int index);
  inline ::ProtoNode* add_nodes_pool();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoNode >&
      nodes_pool() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoNode >*
      mutable_nodes_pool();

  // required int64 last_node = 2;
  inline bool has_last_node() const;
  inline void clear_last_node();
  static const int kLastNodeFieldNumber = 2;
  inline ::google::protobuf::int64 last_node() const;
  inline void set_last_node(::google::protobuf::int64 value);

  // required int64 len_up_to_stop_symbol = 3;
  inline bool has_len_up_to_stop_symbol() const;
  inline void clear_len_up_to_stop_symbol();
  static const int kLenUpToStopSymbolFieldNumber = 3;
  inline ::google::protobuf::int64 len_up_to_stop_symbol() const;
  inline void set_len_up_to_stop_symbol(::google::protobuf::int64 value);

  // required double current_coef = 4;
  inline bool has_current_coef() const;
  inline void clear_current_coef();
  static const int kCurrentCoefFieldNumber = 4;
  inline double current_coef() const;
  inline void set_current_coef(double value);

  // repeated bool is_free_node = 5;
  inline int is_free_node_size() const;
  inline void clear_is_free_node();
  static const int kIsFreeNodeFieldNumber = 5;
  inline bool is_free_node(int index) const;
  inline void set_is_free_node(int index, bool value);
  inline void add_is_free_node(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      is_free_node() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_is_free_node();

  // @@protoc_insertion_point(class_scope:ProtoAutomaton)
 private:
  inline void set_has_last_node();
  inline void clear_has_last_node();
  inline void set_has_len_up_to_stop_symbol();
  inline void clear_has_len_up_to_stop_symbol();
  inline void set_has_current_coef();
  inline void clear_has_current_coef();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ProtoNode > nodes_pool_;
  ::google::protobuf::int64 last_node_;
  ::google::protobuf::int64 len_up_to_stop_symbol_;
  double current_coef_;
  ::google::protobuf::RepeatedField< bool > is_free_node_;
  friend void  protobuf_AddDesc_automaton_2eproto();
  friend void protobuf_AssignDesc_automaton_2eproto();
  friend void protobuf_ShutdownFile_automaton_2eproto();

  void InitAsDefaultInstance();
  static ProtoAutomaton* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoNode_Edge

// required int32 edge_char = 1;
inline bool ProtoNode_Edge::has_edge_char() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoNode_Edge::set_has_edge_char() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoNode_Edge::clear_has_edge_char() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoNode_Edge::clear_edge_char() {
  edge_char_ = 0;
  clear_has_edge_char();
}
inline ::google::protobuf::int32 ProtoNode_Edge::edge_char() const {
  // @@protoc_insertion_point(field_get:ProtoNode.Edge.edge_char)
  return edge_char_;
}
inline void ProtoNode_Edge::set_edge_char(::google::protobuf::int32 value) {
  set_has_edge_char();
  edge_char_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.Edge.edge_char)
}

// required int64 to_node_id = 2;
inline bool ProtoNode_Edge::has_to_node_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoNode_Edge::set_has_to_node_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoNode_Edge::clear_has_to_node_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoNode_Edge::clear_to_node_id() {
  to_node_id_ = GOOGLE_LONGLONG(0);
  clear_has_to_node_id();
}
inline ::google::protobuf::int64 ProtoNode_Edge::to_node_id() const {
  // @@protoc_insertion_point(field_get:ProtoNode.Edge.to_node_id)
  return to_node_id_;
}
inline void ProtoNode_Edge::set_to_node_id(::google::protobuf::int64 value) {
  set_has_to_node_id();
  to_node_id_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.Edge.to_node_id)
}

// -------------------------------------------------------------------

// ProtoNode

// repeated .ProtoNode.Edge edges = 1;
inline int ProtoNode::edges_size() const {
  return edges_.size();
}
inline void ProtoNode::clear_edges() {
  edges_.Clear();
}
inline const ::ProtoNode_Edge& ProtoNode::edges(int index) const {
  // @@protoc_insertion_point(field_get:ProtoNode.edges)
  return edges_.Get(index);
}
inline ::ProtoNode_Edge* ProtoNode::mutable_edges(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoNode.edges)
  return edges_.Mutable(index);
}
inline ::ProtoNode_Edge* ProtoNode::add_edges() {
  // @@protoc_insertion_point(field_add:ProtoNode.edges)
  return edges_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >&
ProtoNode::edges() const {
  // @@protoc_insertion_point(field_list:ProtoNode.edges)
  return edges_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >*
ProtoNode::mutable_edges() {
  // @@protoc_insertion_point(field_mutable_list:ProtoNode.edges)
  return &edges_;
}

// repeated .ProtoNode.Edge rev_edges = 2;
inline int ProtoNode::rev_edges_size() const {
  return rev_edges_.size();
}
inline void ProtoNode::clear_rev_edges() {
  rev_edges_.Clear();
}
inline const ::ProtoNode_Edge& ProtoNode::rev_edges(int index) const {
  // @@protoc_insertion_point(field_get:ProtoNode.rev_edges)
  return rev_edges_.Get(index);
}
inline ::ProtoNode_Edge* ProtoNode::mutable_rev_edges(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoNode.rev_edges)
  return rev_edges_.Mutable(index);
}
inline ::ProtoNode_Edge* ProtoNode::add_rev_edges() {
  // @@protoc_insertion_point(field_add:ProtoNode.rev_edges)
  return rev_edges_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >&
ProtoNode::rev_edges() const {
  // @@protoc_insertion_point(field_list:ProtoNode.rev_edges)
  return rev_edges_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoNode_Edge >*
ProtoNode::mutable_rev_edges() {
  // @@protoc_insertion_point(field_mutable_list:ProtoNode.rev_edges)
  return &rev_edges_;
}

// repeated int64 rev_links = 8;
inline int ProtoNode::rev_links_size() const {
  return rev_links_.size();
}
inline void ProtoNode::clear_rev_links() {
  rev_links_.Clear();
}
inline ::google::protobuf::int64 ProtoNode::rev_links(int index) const {
  // @@protoc_insertion_point(field_get:ProtoNode.rev_links)
  return rev_links_.Get(index);
}
inline void ProtoNode::set_rev_links(int index, ::google::protobuf::int64 value) {
  rev_links_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoNode.rev_links)
}
inline void ProtoNode::add_rev_links(::google::protobuf::int64 value) {
  rev_links_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoNode.rev_links)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ProtoNode::rev_links() const {
  // @@protoc_insertion_point(field_list:ProtoNode.rev_links)
  return rev_links_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ProtoNode::mutable_rev_links() {
  // @@protoc_insertion_point(field_mutable_list:ProtoNode.rev_links)
  return &rev_links_;
}

// required int64 link = 3;
inline bool ProtoNode::has_link() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtoNode::set_has_link() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProtoNode::clear_has_link() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProtoNode::clear_link() {
  link_ = GOOGLE_LONGLONG(0);
  clear_has_link();
}
inline ::google::protobuf::int64 ProtoNode::link() const {
  // @@protoc_insertion_point(field_get:ProtoNode.link)
  return link_;
}
inline void ProtoNode::set_link(::google::protobuf::int64 value) {
  set_has_link();
  link_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.link)
}

// required int64 len_actual = 4;
inline bool ProtoNode::has_len_actual() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProtoNode::set_has_len_actual() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProtoNode::clear_has_len_actual() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProtoNode::clear_len_actual() {
  len_actual_ = GOOGLE_LONGLONG(0);
  clear_has_len_actual();
}
inline ::google::protobuf::int64 ProtoNode::len_actual() const {
  // @@protoc_insertion_point(field_get:ProtoNode.len_actual)
  return len_actual_;
}
inline void ProtoNode::set_len_actual(::google::protobuf::int64 value) {
  set_has_len_actual();
  len_actual_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.len_actual)
}

// required int64 len_within_document = 5;
inline bool ProtoNode::has_len_within_document() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ProtoNode::set_has_len_within_document() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ProtoNode::clear_has_len_within_document() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ProtoNode::clear_len_within_document() {
  len_within_document_ = GOOGLE_LONGLONG(0);
  clear_has_len_within_document();
}
inline ::google::protobuf::int64 ProtoNode::len_within_document() const {
  // @@protoc_insertion_point(field_get:ProtoNode.len_within_document)
  return len_within_document_;
}
inline void ProtoNode::set_len_within_document(::google::protobuf::int64 value) {
  set_has_len_within_document();
  len_within_document_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.len_within_document)
}

// required int64 docs_occurs_in = 6;
inline bool ProtoNode::has_docs_occurs_in() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ProtoNode::set_has_docs_occurs_in() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ProtoNode::clear_has_docs_occurs_in() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ProtoNode::clear_docs_occurs_in() {
  docs_occurs_in_ = GOOGLE_LONGLONG(0);
  clear_has_docs_occurs_in();
}
inline ::google::protobuf::int64 ProtoNode::docs_occurs_in() const {
  // @@protoc_insertion_point(field_get:ProtoNode.docs_occurs_in)
  return docs_occurs_in_;
}
inline void ProtoNode::set_docs_occurs_in(::google::protobuf::int64 value) {
  set_has_docs_occurs_in();
  docs_occurs_in_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.docs_occurs_in)
}

// required double score_occurs_only = 7;
inline bool ProtoNode::has_score_occurs_only() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ProtoNode::set_has_score_occurs_only() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ProtoNode::clear_has_score_occurs_only() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ProtoNode::clear_score_occurs_only() {
  score_occurs_only_ = 0;
  clear_has_score_occurs_only();
}
inline double ProtoNode::score_occurs_only() const {
  // @@protoc_insertion_point(field_get:ProtoNode.score_occurs_only)
  return score_occurs_only_;
}
inline void ProtoNode::set_score_occurs_only(double value) {
  set_has_score_occurs_only();
  score_occurs_only_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.score_occurs_only)
}

// required int64 last_hash = 9;
inline bool ProtoNode::has_last_hash() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ProtoNode::set_has_last_hash() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ProtoNode::clear_has_last_hash() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ProtoNode::clear_last_hash() {
  last_hash_ = GOOGLE_LONGLONG(0);
  clear_has_last_hash();
}
inline ::google::protobuf::int64 ProtoNode::last_hash() const {
  // @@protoc_insertion_point(field_get:ProtoNode.last_hash)
  return last_hash_;
}
inline void ProtoNode::set_last_hash(::google::protobuf::int64 value) {
  set_has_last_hash();
  last_hash_ = value;
  // @@protoc_insertion_point(field_set:ProtoNode.last_hash)
}

// -------------------------------------------------------------------

// ProtoAutomaton

// repeated .ProtoNode nodes_pool = 1;
inline int ProtoAutomaton::nodes_pool_size() const {
  return nodes_pool_.size();
}
inline void ProtoAutomaton::clear_nodes_pool() {
  nodes_pool_.Clear();
}
inline const ::ProtoNode& ProtoAutomaton::nodes_pool(int index) const {
  // @@protoc_insertion_point(field_get:ProtoAutomaton.nodes_pool)
  return nodes_pool_.Get(index);
}
inline ::ProtoNode* ProtoAutomaton::mutable_nodes_pool(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoAutomaton.nodes_pool)
  return nodes_pool_.Mutable(index);
}
inline ::ProtoNode* ProtoAutomaton::add_nodes_pool() {
  // @@protoc_insertion_point(field_add:ProtoAutomaton.nodes_pool)
  return nodes_pool_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoNode >&
ProtoAutomaton::nodes_pool() const {
  // @@protoc_insertion_point(field_list:ProtoAutomaton.nodes_pool)
  return nodes_pool_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoNode >*
ProtoAutomaton::mutable_nodes_pool() {
  // @@protoc_insertion_point(field_mutable_list:ProtoAutomaton.nodes_pool)
  return &nodes_pool_;
}

// required int64 last_node = 2;
inline bool ProtoAutomaton::has_last_node() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoAutomaton::set_has_last_node() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoAutomaton::clear_has_last_node() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoAutomaton::clear_last_node() {
  last_node_ = GOOGLE_LONGLONG(0);
  clear_has_last_node();
}
inline ::google::protobuf::int64 ProtoAutomaton::last_node() const {
  // @@protoc_insertion_point(field_get:ProtoAutomaton.last_node)
  return last_node_;
}
inline void ProtoAutomaton::set_last_node(::google::protobuf::int64 value) {
  set_has_last_node();
  last_node_ = value;
  // @@protoc_insertion_point(field_set:ProtoAutomaton.last_node)
}

// required int64 len_up_to_stop_symbol = 3;
inline bool ProtoAutomaton::has_len_up_to_stop_symbol() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoAutomaton::set_has_len_up_to_stop_symbol() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoAutomaton::clear_has_len_up_to_stop_symbol() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoAutomaton::clear_len_up_to_stop_symbol() {
  len_up_to_stop_symbol_ = GOOGLE_LONGLONG(0);
  clear_has_len_up_to_stop_symbol();
}
inline ::google::protobuf::int64 ProtoAutomaton::len_up_to_stop_symbol() const {
  // @@protoc_insertion_point(field_get:ProtoAutomaton.len_up_to_stop_symbol)
  return len_up_to_stop_symbol_;
}
inline void ProtoAutomaton::set_len_up_to_stop_symbol(::google::protobuf::int64 value) {
  set_has_len_up_to_stop_symbol();
  len_up_to_stop_symbol_ = value;
  // @@protoc_insertion_point(field_set:ProtoAutomaton.len_up_to_stop_symbol)
}

// required double current_coef = 4;
inline bool ProtoAutomaton::has_current_coef() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtoAutomaton::set_has_current_coef() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProtoAutomaton::clear_has_current_coef() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProtoAutomaton::clear_current_coef() {
  current_coef_ = 0;
  clear_has_current_coef();
}
inline double ProtoAutomaton::current_coef() const {
  // @@protoc_insertion_point(field_get:ProtoAutomaton.current_coef)
  return current_coef_;
}
inline void ProtoAutomaton::set_current_coef(double value) {
  set_has_current_coef();
  current_coef_ = value;
  // @@protoc_insertion_point(field_set:ProtoAutomaton.current_coef)
}

// repeated bool is_free_node = 5;
inline int ProtoAutomaton::is_free_node_size() const {
  return is_free_node_.size();
}
inline void ProtoAutomaton::clear_is_free_node() {
  is_free_node_.Clear();
}
inline bool ProtoAutomaton::is_free_node(int index) const {
  // @@protoc_insertion_point(field_get:ProtoAutomaton.is_free_node)
  return is_free_node_.Get(index);
}
inline void ProtoAutomaton::set_is_free_node(int index, bool value) {
  is_free_node_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoAutomaton.is_free_node)
}
inline void ProtoAutomaton::add_is_free_node(bool value) {
  is_free_node_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoAutomaton.is_free_node)
}
inline const ::google::protobuf::RepeatedField< bool >&
ProtoAutomaton::is_free_node() const {
  // @@protoc_insertion_point(field_list:ProtoAutomaton.is_free_node)
  return is_free_node_;
}
inline ::google::protobuf::RepeatedField< bool >*
ProtoAutomaton::mutable_is_free_node() {
  // @@protoc_insertion_point(field_mutable_list:ProtoAutomaton.is_free_node)
  return &is_free_node_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_automaton_2eproto__INCLUDED
